name: Deploy on Main Branch Change

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request
    run: |
      set -e
      curl -X GET "${{ secrets.UPDATER_URL }}" \
        -H "x-api-key: ${{ secrets.AUTOMATION_KEY }}"
